---
# Set password for grub version 2

- block:
    - name: Check if password is already configured
      command: "cat {{ grub_options_password_config_file_v2 }}"
      changed_when: no
      register: grub_options_check_password_result

    - block:
        - name: Generate password
          expect:
            command: "grub2-mkpasswd-pbkdf2"
            responses:
              ":": "{{ grup_options_password }}"
          register: grub2_password_generate_result

        - name: Setup config file for password
          template:
            src: users.j2
            dest: "{{ grub_options_password_config_file_v2 }}"
          notify: generate grub2 config
          vars:
            grub_options_password: >-
              {{ grub2_password_generate_result.stdout.split(' ') | last }}
      when: >-
        grub_options_check_password_result.stdout
        is not search("grub.pbkdf2.sha512")
        or grub_options_set_password_force
  tags:
    - role::grup_options::password
