---
# Set password for grub version 2
- block:
    - name: check if password is already configured
      command: "cat {{ grub_options_password_config_file_v2 }} "
      register: grub_options_check_password_result

    - name: Generate password
      expect:
        command: "grub2-mkpasswd-pbkdf2"
        responses:
          (?i)contraseña: "changeme"
          (?i)password: "changeme"
      register: grub2_password_generate_result
      when: (grub_options_check_password_result.stdout is not search("grub.pbkdf2.sha512")) or
            (grub_options_password_forced)

    - name: register grub password
      set_fact:
        grub_options_password: "{{ grub2_password_generate_result.stdout.split(' ') | last }}"
      when: (grub_options_check_password_result.stdout is not search("grub.pbkdf2.sha512")) or
            (grub_options_password_forced)


    - name: Set config file to set password
      template:
        src: 01_users.j2
        dest: "{{ grub_options_password_config_file_v2 }}"
      notify: grub_options apply grub2 changes
      when: (grub_options_check_password_result.stdout is not search("grub.pbkdf2.sha512")) or
            (grub_options_password_forced)

  tags:
    - role::grup_options::password
