---
# Set password for grub version 1

- block:
    - name: Check if password is already configured
      command: "cat {{ grub_options_password_config_file_v1 }}"
      changed_when: no
      register: grub_options_check_password_result

    - block:
        - name: Generate password
          expect:
            command: "grub-md5-crypt"
            responses:
              ":": "{{ grup_options_password }}"
          register: grub_password_generate_result

        - name: Setup grub password
          lineinfile:
            dest: "{{ grub_options_password_config_file_v1 }}"
            regexp: "^password "
            state: present
            line: "password --md5 {{ grub_options_password }}"
            insertafter: "^timeout"
          vars:
            grub_options_password: >-
              {{ grub_password_generate_result.stdout.split(' ') | last }}
      when: >-
        grub_options_check_password_result.stdout
        is not search("password --md5")
        or grub_options_set_password_force
  tags:
    - role::grup_options::password
