---
# Set password for grub version 1
- block:
    - name: check if password is already configured
      command: "cat {{ grub_options_password_config_file_v1 }} "
      register: grub_options_check_password_result

    - name: Generate password
      expect:
        command: "grub-md5-crypt"
        responses:
          (?i)contraseña: "changeme"
          (?i)password: "changeme"
      register: grub_password_generate_result
      when: (grub_options_check_password_result.stdout is not search("password --md5")) or
            (grub_options_password_forced)

    - name: register grub password
      set_fact:
        grub_options_password: "{{ grub2_password_generate_result.stdout.split(' ') | last }}"
      when: (grub_options_check_password_result.stdout is not search("password --md5")) or
            (grub_options_password_forced)

    - name: "grub v1 | add password"
      lineinfile:
        dest: "{{ grub_options_password_config_file_v1 }}"
        regexp: '^password '
        state: present
        line: 'password --md5 {{ grub_options_password }}'
        insertafter: '^timeout'
      when: (grub_options_check_password_result.stdout is not search("password --md5")) or
            (grub_options_password_forced)

  tags:
    - role::grup_options::password
