---
# Role tasks

- block:
    - name: read grub config file
      command: "cat {{ grub_config_file }}"
      changed_when: false
      register: grub_options_read_config_file_result

    - name: add grub options
      command: /sbin/grubby --args="{{ item }}" --update-kernel=ALL
      register: grub_options_add_result
      when: >-
        grub_options_read_config_file_result.stdout_lines
        | select("search", grup_config_options_prefix + " .*")
        | select("search", "^((?!" + item + ").)*$")
        | list
        | length > 0
      with_items: "{{ grub_options_present }}"

    - name: remove grub options
      command: /sbin/grubby --remove-args="{{ item }}" --update-kernel=ALL
      register: grub_options_remove_result
      when: >-
        grub_options_read_config_file_result.stdout_lines
        | select("search", grup_config_options_prefix + " .*")
        | select("search", item)
        | list
        | length > 0
      with_items: "{{ grub_options_absent }}"

    - name: save old version of grub config file
      copy:
        dest: "{{ grub_config_file + '.' + '%Y%m%d%H%M%S' | strftime }}"
        content: "{{ grub_options_read_config_file_result.stdout }}"
      when: >-
        grub_options_add_result is changed
        or grub_options_remove_result is changed
  vars:
    grub_config_file: >-
      {{ (ansible_facts.distribution | lower in ["centos", "rhel"]
          and ansible_facts.distribution_major_version is version("6", "<="))
         | ternary(grub_options_config_file_v1, grub_options_config_file_v2) }}

    grup_config_options_prefix: >-
      {{ (grub_config_file == grub_options_config_file_v1)
         | ternary("kernel", "linux") }}
  tags:
    - role::grup_options
