---
# Role tasks for grub configuration

- debug:
    msg: "Distribucion: {{ ansible_distribution }}"

- debug:
    msg: "Major version: {{ ansible_distribution_major_version }}"

- name: install necessary packages
  package:
    name: "{{ item }}"
    state: present
  with_items: >-
      {{ grub_packages[distro_packages_key] }}
  vars:
    distro_packages_key: >-
      {{ ansible_distribution | lower + "_" + ansible_distribution_major_version }}

- name: backup grup config file
  become: true
  shell: "cp {{ grub_config_file }} {{ grub_config_file }}.`date +%Y%m%d%H%M%S`"
  vars:
      grub_config_file: >-
        {{ (ansible_distribution | lower in ["rhel", "centos"] and ansible_distribution_major_version <= 6)
           | ternary(grub_config_file_v1, grub_config_file_v2) }}

- debug:
      var: copy_file_result

- name: add Grub requiered options
  become: true
  shell: /sbin/grubby --args="{{ item }}" --update-kernel=ALL
  with_items: "{{ grub_options_to_be_present }}"

- name: remove Grub options
  become: true
  shell: /sbin/grubby --remove-args="{{ item }}" --update-kernel=ALL
  with_items: "{{ grub_options_to_be_absent }}"
