---
# Role tasks

- include_role:
    name: amtega.check_platform
  vars:
    check_platform_distributions:
      centos: 6
      fedora: 27
      redhat: 6

- include_role:
    name: amtega.packages
  vars:
    packages_os:
      centos:
        6:
          "grub": present
          "grubby": present
        7:
          "grub2": present
          "grub2-tools": present
          "grubby": present
      fedora:
        all:
          "grub2": present
          "grub2-tools": present
          "grubby": present
      redhat:
        all:
          "grub": present
          "grubby": present
        7:
          "grub2": present
          "grub2-tools": present
          "grubby": present

- block:
    - name: read grub config file
      command: "cat {{ grub_config_file }}"
      changed_when: false
      register: grub_options_read_config_file_result

    - name: add grub options
      shell: >-
        /sbin/grubby
        --args="{{ grub_options_item }}"
        --update-kernel=ALL
        --config-file={{ grub_config_file }} &&
        cat {{ grub_config_file }}
      args:
        warn: no
      register: grub_options_add_result
      changed_when: >-
        grub_options_read_config_file_result.stdout
        != grub_options_add_result.stdout
      when: >-
        grub_options_read_config_file_result.stdout_lines
        | select("search", grup_config_options_prefix + " .*")
        | select("search", "^((?!" + grub_options_item + ").)*$")
        | list
        | length > 0
      loop: "{{ grub_options_present }}"
      loop_control:
        loop_var: grub_options_item

    - name: remove grub options
      shell: >-
        /sbin/grubby
        --remove-args="{{ grub_options_item }}"
        --update-kernel=ALL
        --config-file={{ grub_config_file }} &&
        cat {{ grub_config_file }}
      args:
        warn: no
      changed_when: >-
        grub_options_read_config_file_result.stdout
        != grub_options_remove_result.stdout
      register: grub_options_remove_result
      when: >-
        grub_options_read_config_file_result.stdout_lines
        | select("search", grup_config_options_prefix + " .*")
        | select("search", grub_options_item)
        | list
        | length > 0
      loop: "{{ grub_options_absent }}"
      loop_control:
        loop_var: grub_options_item

    - name: save old version of grub config file
      copy:
        dest: "{{ grub_config_file + '.' + '%Y%m%d%H%M%S' | strftime }}"
        content: "{{ grub_options_read_config_file_result.stdout }}"
      when: >-
        grub_options_add_result is changed
        or grub_options_remove_result is changed
  vars:
    grub_config_file: >-
      {{ (ansible_facts.distribution | lower in ["centos", "redhat"]
          and ansible_facts.distribution_major_version is version("6", "<="))
         | ternary(grub_options_config_file_v1, grub_options_config_file_v2) }}

    grup_config_options_prefix: >-
      {{ (grub_config_file == grub_options_config_file_v1)
         | ternary("kernel", "linux") }}
  tags:
    - role::grup_options
